##

[[server]]
name = "Local"
description = "LXC running komodo"
tags = ["infra"]
[server.config]
region = "Arkay"
enabled = true
external_address = "[fd67:84d2:d793:0:be24:11ff:fe05:99a7]"

##

[[server]]
name = "vm-docker-01"
description = "Primary docker VM for critical services"
tags = ["infra"]
[server.config]
region = "Arkay"
enabled = true
external_address = "[fd67:84d2:d793:0:68:49ff:fe55:c283]"

##

[[server]]
name = "boethiah"
description = "Raspberry Pi running Technitium DNS server"
tags = ["infra"]
[server.config]
region = "Boethiah"
enabled = true
external_address = "[fd67:84d2:d793:0:4a03:c729:7976:2e1]"

##

[[server]]
name = "ct-media-servarr-02"
description = "LXC running servarr stack for media"
tags = ["media"]
[server.config]
region = "Arkay"
enabled = true
external_address = "[fd67:84d2:d793:0:be24:11ff:feb0:62da]"