##

[[stack]]
name = "servarr"
description = "Servarr stack for media"
deploy = true
tags = ["media"]
[stack.config]
auto_update = true
server = "ct-media-servarr-02"
links = ["https://wiki.servarr.com/"]

# Git configuration
git_provider = "github.com"
repo = "AnOliveBranch/homelab"
branch = "main"
run_directory = "komodo/stacks"
file_paths = ["servarr-compose.yaml"]
