##

[[stack]]
name = "authentication"
description = "Authentik stack"
deploy = true
tags = ["infra"]
[stack.config]
auto_update = true
server = "vm-docker-01"
links = ["https://docs.goauthentik.io/"]
environment = """
  POSTGRES_PASSWORD=[[AUTHENTIK_POSTGRES_PASSWORD]]
  AUTHENTIK_POSTGRESQL__PASSWORD=[[AUTHENTIK_POSTGRES_PASSWORD]]
  AUTHENTIK_SECRET_KEY=[[AUTHENTIK_SERVER_SECRET_KEY]]
  AUTHENTIK_EMAIL__PASSWORD=[[AUTHENTIK_SMTP_PASSWORD]]
"""

# Git configuration
git_provider = "github.com"
repo = "AnOliveBranch/homelab"
branch = "main"
run_directory = "komodo/stacks"
file_paths = ["authentik-compose.yaml"]

##

[[stack]]
name = "dns-ns0"
description = "Technitium DNS Server"
deploy = true
tags = ["infra", "networking"]
[stack.config]
auto_update = true
server = "vm-docker-01"
links = ["https://technitium.com/dns/"]
environment = """
  DNS_SERVER_DOMAIN=ns0.dns.local
"""

# Git configuration
git_provider = "github.com"
repo = "AnOliveBranch/homelab"
branch = "main"
run_directory = "komodo/stacks"
file_paths = ["technitium-compose.yaml"]

##
[[stack]]

name = "dns-ns2"
description = "Technitium DNS Server"
deploy = true
tags = ["infra", "networking"]
[stack.config]
auto_update = true
server = "boethiah"
links = ["https://technitium.com/dns/"]
environment = """
  DNS_SERVER_DOMAIN=ns2.dns.local
"""

# Git configuration
git_provider = "github.com"
repo = "AnOliveBranch/homelab"
branch = "main"
run_directory = "komodo/stacks"
file_paths = ["technitium-compose.yaml"]

##

[[stack]]
name = "servarr"
description = "Servarr stack for media"
deploy = true
tags = ["media"]
[stack.config]
auto_update = true
server = "ct-media-servarr-02"
links = ["https://wiki.servarr.com/"]

# Git configuration
git_provider = "github.com"
repo = "AnOliveBranch/homelab"
branch = "main"
run_directory = "komodo/stacks"
file_paths = ["servarr-compose.yaml"]

##

[[stack]]
name = "media"
description = "Media stack (streamystats & seerr)"
deploy = true
tags = ["media"]
[stack.config]
auto_update = true
server = "vm-docker-01"
links = ["https://github.com/fredrikburmester/streamystats","https://docs.seerr.dev/"]
environment = """
  POSTGRES_PASSWORD=[[STREAMYSTATS_POSTGRES_DB_PASSWORD]]
  SESSION_SECRET=[[STREAMYSTATS_SESSION_SECRET]]
  NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=[[STREAMYSTATS_ENCRYPTION_KEY]]
"""

# Git configuration
git_provider = "github.com"
repo = "AnOliveBranch/homelab"
branch = "main"
run_directory = "komodo/stacks"
file_paths = ["media-compose.yaml"]

##

[[stack]]
name = "ntfy-alerter"
description = "Custom alerter to integrate with ntfy"
deploy = true
tags = ["infra"]
[stack.config]
auto_update = true
server = "Local"
links = ["https://github.com/FoxxMD/deploy-ntfy-alerter/tree/main"]
environment = """
  NTFY_TOKEN=[[NTFY_TOKEN]]
"""

# Git configuration
git_provider = "github.com"
repo = "AnOliveBranch/homelab"
branch = "main"
run_directory = "komodo/stacks"
file_paths = ["ntfy-alerter-compose.yaml"]

