# Run with docker compose up -d
services:
  dozzle:
    restart: unless-stopped
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle_data:/data
    ports:
      - 1024:8080
  pulse:
    restart: unless-stopped
    image: rcourtman/pulse:latest
    volumes:
      - pulse_data:/data
    ports:
      - 7655:7655
  uptime-kuma:
    restart: unless-stopped
    image: louislam/uptime-kuma:2
    ports:
      - 3001:3001
    volumes:
      - uptime_kuma_data:/app/data
volumes:
  dozzle_data:
  pulse_data:
  uptime_kuma_data:

