services:
  authentik-postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: [[AUTHENTIK_POSTGRES_DB_NAME]]
      POSTGRES_USER: [[AUTHENTIK_POSTGRES_DB_USER]]
      POSTGRES_PASSWORD: [[AUTHENTIK_POSTGRES_DB_PASSWORD]]
    volumes:
      - authentik-db:/var/lib/postgresql/data
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d [[AUTHENTIK_POSTGRES_DB_NAME]] -U [[AUTHENTIK_POSTGRES_DB_USER]]
      timeout: 5s
    networks:
      - authentik-net
  authentik-server:
    image: ghcr.io/goauthentik/server:2026.5.3
    command: server
    restart: unless-stopped
    environment:
      AUTHENTIK_SECRET_KEY: [[AUTHENTIK_SERVER_SECRET_KEY]]
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: [[AUTHENTIK_POSTGRES_DB_NAME]]
      AUTHENTIK_POSTGRESQL__USER: [[AUTHENTIK_POSTGRES_DB_USER]]
      AUTHENTIK_POSTGRESQL__PASSWORD: [[AUTHENTIK_POSTGRES_DB_PASSWORD]]
      AUTHENTIK_EMAIL__USE_TLS: true
      AUTHENTIK_EMAIL__HOST: [[GLOBAL_SMTP_HOST]]
      AUTHENTIK_EMAIL__PORT: [[GLOBAL_SMTP_PORT]]
      AUTHENTIK_EMAIL__USERNAME: [[GLOBAL_SMTP_USERNAME]]
      AUTHENTIK_EMAIL__FROM: [[GLOBAL_SMTP_USERNAME]]
      AUTHENTIK_EMAIL__PASSWORD: [[AUTHENTIK_SMTP_PASSWORD]]
    ports:
      - 9000:9000
      - 9443:9443
    depends_on:
      authentik-postgres:
        condition: service_healthy
    shm_size: 512mb
    volumes:
      - authentik-data:/data
      - authentik-templates:/templates
      - authentik-media:/media
    networks:
      - authentik-net
  authentik-worker:
    image: ghcr.io/goauthentik/server:2026.5.3
    command: worker
    restart: unless-stopped
    environment:
      AUTHENTIK_SECRET_KEY: [[AUTHENTIK_SERVER_SECRET_KEY]]
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: [[AUTHENTIK_POSTGRES_DB_NAME]]
      AUTHENTIK_POSTGRESQL__USER: [[AUTHENTIK_POSTGRES_DB_USER]]
      AUTHENTIK_POSTGRESQL__PASSWORD: [[AUTHENTIK_POSTGRES_DB_PASSWORD]]
      AUTHENTIK_EMAIL__USE_TLS: true
      AUTHENTIK_EMAIL__HOST: [[GLOBAL_SMTP_HOST]]
      AUTHENTIK_EMAIL__PORT: [[GLOBAL_SMTP_PORT]]
      AUTHENTIK_EMAIL__USERNAME: [[GLOBAL_SMTP_USERNAME]]
      AUTHENTIK_EMAIL__FROM: [[GLOBAL_SMTP_USERNAME]]
      AUTHENTIK_EMAIL__PASSWORD: [[AUTHENTIK_SMTP_PASSWORD]]
    shm_size: 512mb
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik-data:/data
      - authentik-certs:/certs
      - authentik-templates:/templates
    depends_on:
      authentik-postgres:
        condition: service_healthy
    networks:
      - authentik-net

networks:
  authentik-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "[[AUTHENTIK_IPV6_PREFIX]]::/64"
          gateway: "[[AUTHENTIK_IPV6_PREFIX]]::1"

volumes:
  authentik-db:
    driver: local
  authentik-data:
  authentik-certs:
  authentik-templates:
  authentik-media:
