services:
  authentik-postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
    volumes:
      - authentik-db:/var/lib/postgresql/data
  authentik-server:
    image: ghcr.io/goauthentik/server:2026.5.4
    command: server
    restart: unless-stopped
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_EMAIL__USE_TLS: true
      AUTHENTIK_EMAIL__HOST: smtp.protonmail.ch
      AUTHENTIK_EMAIL__PORT: 587
      AUTHENTIK_EMAIL__USERNAME: contact@anolivebranch.dev
      AUTHENTIK_EMAIL__FROM: contact@anolivebranch.dev
    ports:
      - 9000:9000
      - 9443:9443
    depends_on:
      authentik-postgres:
        condition: service_healthy
    shm_size: 512mb
    volumes:
      - authentik-data:/data
      - authentik-templates:/templates
      - authentik-media:/media
  authentik-worker:
    image: ghcr.io/goauthentik/server:2026.5.4
    command: worker
    restart: unless-stopped
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_EMAIL__USE_TLS: true
      AUTHENTIK_EMAIL__HOST: smtp.protonmail.ch
      AUTHENTIK_EMAIL__PORT: 587
      AUTHENTIK_EMAIL__USERNAME: contact@anolivebranch.dev
      AUTHENTIK_EMAIL__FROM: contact@anolivebranch.dev
    shm_size: 512mb
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - authentik-data:/data
      - authentik-certs:/certs
      - authentik-templates:/templates
    depends_on:
      authentik-postgres:
        condition: service_healthy

volumes:
  authentik-db:
    driver: local
  authentik-data:
  authentik-certs:
  authentik-templates:
  authentik-media:
