services:
  #  Download clients
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    volumes:
      - qbittorrent-config:/config
      - /mnt/servarr/torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - servarr-net
    restart: unless-stopped
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - nzbget-config:/config
      - /mnt/servarr/usenet:/data/usenet
    ports:
      - 6789:6789
    networks:
      - servarr-net
    restart: unless-stopped
  # Index Manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    networks:
      - servarr-net
    restart: unless-stopped
  # Get around CloudFlare protection
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      TZ: America/Chicago
    ports:
      - 8191:8191
    volumes:
      - flaresolverr-config:/config
    networks:
      - servarr-net
    restart: unless-stopped
  # Media Management
  # Movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - radarr-config:/config
      - /mnt/servarr:/data
    ports:
      - 7878:7878
    networks:
      - servarr-net
    restart: unless-stopped
  # TV Shows
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - sonarr-config:/config
      - /mnt/servarr:/data
    ports:
      - 8989:8989
    networks:
      - servarr-net
    restart: unless-stopped
  # Music
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - lidarr-config:/config
      - /mnt/servarr:/data
    ports:
      - 8686:8686
    networks:
      - servarr-net
    restart: unless-stopped
  # Subtitles
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - bazarr-config:/config
      - /mnt/servarr:/data
    ports:
      - 6767:6767
    networks:
      - servarr-net
    restart: unless-stopped

networks:
  servarr-net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd67:84d2:d793:9dfa::/64"
          gateway: "fd67:84d2:d793:9dfa::1"

volumes:
  qbittorrent-config:
  nzbget-config:
  prowlarr-config:
  flaresolverr-config:
  sonarr-config:
  radarr-config:
  lidarr-config:
  bazarr-config:
